services:
  db:
    image: postgres:15
    container_name: inova_db
    environment:
      - POSTGRES_DB=inova_db
      - POSTGRES_USER=inova_user
      - POSTGRES_PASSWORD=inova_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: inova_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "SECRET_KEY=${SECRET_KEY}"
      - "DEBUG=${DEBUG}"
      - "SETTINGS_MODULE=${SETTINGS_MODULE}"
      - POSTGRES_USER=inova_user
      - POSTGRES_PASSWORD=inova_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
